{
 "title": "initial SSRC variable definition",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Select job",
    "query": {
     "query": "{instance=\"localhost:9568\"}"
    }
   },
   {
    "name": "SSRC",
    "label": "Select SSRC",
    "query": {
     "query": "{job=\"$job\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "bytes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "inboundrtp_bytes_received{ssrc=\"$SSRC\"}"
    }
   ]
  },
  {
   "title": "frames received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{__name__=~\"inboundrtp_OPUS_frames|inboundrtp_VP8_frames\", ssrc=\"$SSRC\"}"
    }
   ]
  },
  {
   "title": "keyframes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "inboundrtp_VP8_keyframes{ssrc=\"$SSRC\"}"
    }
   ]
  },
  {
   "title": "keyframe request sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "inboundrtp_keyframe_request_sent{ssrc=\"$SSRC\"}"
    }
   ]
  }
 ]
}