/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfish Videoroom
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "./configuration";
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "./common";
import type { RequestArgs } from "./base";
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from "./base";

/**
 * RoomApi - axios parameter creator
 * @export
 */
export const RoomApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Create a new peer in a room and get its token
     * @summary Join a room
     * @param {string} roomId Room ID
     * @param {any} [body] Room params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    videoroomWebRoomControllerShow: async (
      roomId: string,
      body?: any,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'roomId' is not null or undefined
      assertParamExists("videoroomWebRoomControllerShow", "roomId", roomId);
      const localVarPath = `/api/room/{room_id}`.replace(`{${"room_id"}}`, encodeURIComponent(String(roomId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: "GET", ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
      localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration);

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * RoomApi - functional programming interface
 * @export
 */
export const RoomApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = RoomApiAxiosParamCreator(configuration);
  return {
    /**
     * Create a new peer in a room and get its token
     * @summary Join a room
     * @param {string} roomId Room ID
     * @param {any} [body] Room params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async videoroomWebRoomControllerShow(
      roomId: string,
      body?: any,
      options?: AxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.videoroomWebRoomControllerShow(roomId, body, options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
  };
};

/**
 * RoomApi - factory interface
 * @export
 */
export const RoomApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = RoomApiFp(configuration);
  return {
    /**
     * Create a new peer in a room and get its token
     * @summary Join a room
     * @param {string} roomId Room ID
     * @param {any} [body] Room params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    videoroomWebRoomControllerShow(roomId: string, body?: any, options?: any): AxiosPromise<string> {
      return localVarFp
        .videoroomWebRoomControllerShow(roomId, body, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * RoomApi - object-oriented interface
 * @export
 * @class RoomApi
 * @extends {BaseAPI}
 */
export class RoomApi extends BaseAPI {
  /**
   * Create a new peer in a room and get its token
   * @summary Join a room
   * @param {string} roomId Room ID
   * @param {any} [body] Room params
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RoomApi
   */
  public videoroomWebRoomControllerShow(roomId: string, body?: any, options?: AxiosRequestConfig) {
    return RoomApiFp(this.configuration)
      .videoroomWebRoomControllerShow(roomId, body, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
